# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0005_posicion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posicion',
            new_name='Clasificacion',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='clasificacion',
            new_name='posicion',
        ),
    ]
