# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0006_auto_20170121_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificacion',
            name='numero',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='posicion',
            new_name='puntos',
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
    ]
