# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0007_auto_20170123_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='jugadores',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='equipo',
            field=models.ManyToManyField(to='apk.Equipo'),
        ),
    ]
