# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0013_auto_20170125_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
