# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0015_remove_jugadores_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='pos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
