# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0016_auto_20170125_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='equipo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(to='apk.Jugadores'),
        ),
    ]
