# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0017_auto_20170125_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='jugadores',
            new_name='plantilla',
        ),
    ]
