# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0019_partidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidos',
            name='resultado',
            field=models.CharField(default='0  -  0', max_length=10),
        ),
    ]
