# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0020_partidos_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidos',
            name='arbitro',
            field=models.CharField(default='', max_length=20),
        ),
    ]
