# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0022_auto_20170126_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidos',
            name='dia',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
