# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0024_auto_20170126_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidos',
            name='dia',
            field=models.DateField(),
        ),
    ]
