# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0025_auto_20170126_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='apk/static/imagenes/'),
        ),
    ]
